# http://graphite.wikidot.com/installation
---
- hosts: all
  user: jwallace
  sudo: yes
  tasks:
  - name: We need git, and some python tools
    yum: pkg={{ item }} state=installed
    with_items:
    - git
    - python-setuptools
    - python-twisted
    - python-memcached
    - pycairo
    - bitmap-fonts-compat
    - libevent-devel
    - python-devel

  - name: Install pip
    easy_install: name=pip

  - name: Upgrade setuptools (1/2)
    pip: name=setuptools extra_args='--upgrade --no-use-wheel'

  - name: Upgrade setuptools (2/2)
    pip: name=setuptools extra_args='--upgrade --no-use-wheel'

  - name: Use pip to install needed python libraries
    pip: name={{ item }} use_mirrors=no
    with_items:
    - django
    - django-tagging
    - uwsgi

  - name: Copy the uWSGI init script over
    copy: src=/etc/ansible/filestore/uwsgi-init dest=/etc/init.d/uwsgi mode=0755

  - name: Copy the uWSGI Nginx/Django INI file over
    copy: src=/etc/ansible/filestore/

  - name: Download whisper (stable version)
    git: repo=https://github.com/graphite-project/whisper.git dest=/tmp/whisper version=0.9.x

  - name: Install whisper
    command: chdir=/tmp/whisper python setup.py install

  - name: Download carbon
    git: repo=https://github.com/graphite-project/carbon.git dest=/tmp/carbon version=0.9.x

  - name: Install carbon
    command: chdir=/tmp/carbon python setup.py install

  - name: Configure carbon (1/2)
    command: chdir=/opt/graphite/conf creates=carbon.conf cp carbon.conf.example carbon.conf

  - name: Configure carbon (2/2)
    command: chdir=/opt/graphite/conf creates=storage-schemas.conf cp storage-schemas.conf.example storage-schemas.conf

  - name: Download graphite-web
    git: repo=https://github.com/graphite-project/graphite-web.git dest=/tmp/graphite-web version=0.9.x

  - name: Install graphite-web
    command: chdir=/tmp/graphite-web python setup.py install

  - name: Download EPEL Repo
    get_url: dest=/tmp/epel-release.rpm url=http://download.fedoraproject.org/pub/epel/6/i386/epel-release-6-8.noarch.rpm

  - name: Install EPEL Repo
    yum: pkg=/tmp/epel-release.rpm state=installed

  - name: Install nginx
    yum: pkg=nginx state=installed

  - name: Install the graphite nginx config
    copy: src=/etc/ansible/filestore/graphite.conf dest=/etc/nginx/conf.d/graphite.conf

#  - name: Set nginx to start at boot

#  - name: Initialize the SQLite DB
    #command: chdir=/opt/graphite/webapp/graphite python manage.py syncdb
