---
- hosts: all
  user: jwallace
  sudo: yes
  tasks:
  - name: Install Required Packages
    yum: pkg={{ item }} state=installed
    with_items:
    - git

- hosts: all
  user: jwallace
  tasks:
  - name: Checkout the HomeSHick Git
    git: repo=git://github.com/andsens/homeshick.git dest=/home/jwallace/.homesick/repos/homeshick

  - name: Update bashrc to have homeshick initialization
    lineinfile: dest=/home/jwallace/.bashrc line="source $HOME/.homesick/repos/homeshick/homeshick.sh" regexp='homeshick'

  - name: Clone my dotfile Repo
    git: repo=git://github.com/fdask/dotfiles.git dest=/home/jwallace/.homesick/repos/dotfiles accept_hostkey=true

  - name: Link out dotfiles
    command: /home/jwallace/.homesick/repos/homeshick/bin/homeshick link dotfiles -f -q
