# http://graphite.wikidot.com/installation
---
- hosts: all
  user: jwallace
  sudo: yes
  tasks:
# machine NEEDS to be 64bits!  test for that
  - name: Make sure Python SELinux bindinds are installed
    yum: pkg=libselinux-python state=installed

  - name: Check to see if SELinux is installed
    stat: path=/etc/selinux/config
    register: seconf

  - name: Disable SELinux
    lineinfile: dest=/etc/selinux/config regexp=^SELINUX= line=SELINUX=disabled
    when: seconf.stat.exists is defined and seconf.stat.exists == true

  - name: Install mongo repo
    copy: src=filestore/mongo.repo dest=/etc/yum.repos.d/mongo.repo owner=root group=root mode=644

  - name: Install mongo packages
    yum: pkg={{ item }} state=installed
    with_items:
    - mongo-10gen 
    - mongo-10gen-server

  - name: Set mongo server to start at boot
    service: name=mongod state=started enabled=yes

  - name: install php-pear (for pecl)
    yum: pkg={{ item }} state=installed
    with_items:
    - php-pear
    - php-devel

   # this may prompt for some enterprise shit, holding up the install!
   # try printf "\n" | pecl install apc
  - name: install the mondo bindings from pecl
    command: pecl install mongo
    register: peclmongo

  - name: copy over the ini file
    copy: src=./filestore/mongo.ini dest=/etc/php.d/mongo.ini mode=0644

  - name: debug shit
    debug: var=peclmongo

  - name: restart php-fpm
    service: name=php-fpm state=restarted enabled=yes
    when: peclmongo.changed
