---
- hosts: all
  sudo: yes
  tasks:
  - include: centos6.8-epel.yml
    when: ansible_distribution == 'CentOS' and {{ ansible_distribution_version | version_compare('7.0', '<') }} == 'True'

  - include: centos7-epel.yml
    when: ansible_distribution == 'CentOS' and {{ ansible_distribution_version | version_compare('7.0', '>=') }} == 'True'

  - name: Install the nginx/php-fpm packages from Yum
    yum: pkg={{ item }} state=installed
    with_items:
    - nginx
    - php-fpm

  - name: Install Nginx.conf to Enable PHP-FPM
    copy: src=filestore/nginx_default.conf dest=/etc/nginx/conf.d/default.conf owner=root group=root mode=644
    notify: 
      - restart nginx

  - name: Edit php-fpm.d/www.conf to change user to nginx
    lineinfile: dest=/etc/php-fpm.d/www.conf regexp="^user = apache" line="user = nginx"
  
  - name: Edit php-fpm.d/www.conf to change group to nginx
    lineinfile: dest=/etc/php-fpm.d/www.conf regexp="^group = apache" line="group = nginx"

  - name: Set the services to start at boot
    service: name={{ item }} enabled=yes state=started
    with_items:
    - nginx
    - php-fpm

  handlers:
  - name: restart nginx
    service: name=nginx state=restarted
