---
- hosts: all
  sudo: yes
  vars:
    major_dist_version: "{{ ansible_distribution_version|truncate(1, True, '')|int }}"
  tasks:
  - debug: msg="{{major_dist_version}}"

  - name: Disable SELinux
    selinux: state=disabled

  - include: centos6.8-epel.yml
    when: ansible_distribution == 'CentOS' and major_dist_version == "6"

  - include: centos7-epel.yml
    when: ansible_distribution == 'CentOS' and major_dist_version == "7"

  - name: Install the nginx/php-fpm packages from Yum
    yum: pkg={{ item }} state=installed
    with_items:
    - nginx
    - php-fpm

  - name: Install Nginx.conf to Enable PHP-FPM
    copy: src=filestore/nginx_default.conf dest=/etc/nginx/conf.d/default.conf owner=root group=root mode=644
    notify: 
      - restart nginx

  - name: Edit php-fpm.d/www.conf to change user to nginx
    lineinfile: dest=/etc/php-fpm.d/www.conf regexp="^user = apache" line="user = nginx"
  
  - name: Edit php-fpm.d/www.conf to change group to nginx
    lineinfile: dest=/etc/php-fpm.d/www.conf regexp="^group = apache" line="group = nginx"

  - name: Set the services to start at boot
    service: name={{ item }} enabled=yes state=started
    with_items:
    - nginx
    - php-fpm

  - name: Add exception for web traffic to firewalld
    firewalld: service=https permanent=true state=enabled immediate=yes
    firewalld: service=http permanent=true state=enabled immediate=yes
    #when: ansible_distribution == 'CentOS' and major_dist_version == "7" and firewalld_result.stdout == "active"

  handlers:
  - name: restart nginx
    service: name=nginx state=restarted
