---
- hosts: all
  user: jwallace
  sudo: yes
  gather_facts: no
  tasks:
#  - name: Install user 'jwallace'
#    user: name=jwallace password='$1$SALT$7DlqNtINMt/Wr6CigkiCK.' groups=wheel
#
#  - name: Install SSH key in authorized_keys
#    authorized_key: user=jwallace key="{{ lookup('file', '/home/jwallace/.ssh/id_rsa.pub') }}"
#
  - name: Disable SELinux
    lineinfile: dest=/etc/selinux/config regexp=^SELINUX= line=SELINUX=disabled

#  - name: Enable SUDO access for Wheel group
#    lineinfile: dest=/etc/sudoers state=present regexp='# %wheel   ALL\=\(ALL\)   NOPASSWD' line='%wheel ALL=(ALL) NOPASSWD:ALL' validate='visudo -cf %s'

  - name: Disable IPTables
    service: name=iptables state=stopped

  - name: Download EPEL Repo
    get_url: dest=/tmp/epel-release.rpm url=http://download.fedoraproject.org/pub/epel/6/i386/epel-release-6-8.noarch.rpm

  - name: Install EPEL Repo
    yum: pkg=/tmp/epel-release.rpm state=installed

  - name: Pull standard packages
    yum: pkg={{ item }} state=installed
    with_items:
    - screen
    - wget
    - git
    - vim
    - nc

#  - include: sensu-server.yml

#  Generate password with the following command:
#  openssl passwd -salt ANYTHING -1 PASSWORD

  - name: Install NodeJS
    yum: pkg=npm state=installed

  # INSTALL HOMESHICK
- include: homeshick.yml 

# varnish server
# monitoring on varnish and webserver
