#!/bin/bash
#
# /etc/rc.d/init.d/uwsgi
# This shell script takes care of starting and stopping
# ns-slapd (the Fedora Directory Server)
#
# Author: James Wallace <sausages@gmail.com>
#
# chkconfig: 2345 13 87
# description: Start uwsgi

# Source function library.
. /etc/init.d/functions

PROG=uwsgi
DIR=/usr/local/bin
PIDFILE=/var/run/$PROG.pid
LOGFILE=/var/log/$PROG.log
OPTIONS="--ini /opt/graphite/conf/graphite.ini --daemonize $LOGFILE"

if [ -f /etc/sysconfig/uwsgi ]; then
	. /etc/sysconfig/uwsgi
fi

start() {
	echo -n "Starting $PROG: "

	if [ -f $PIDFILE ]; then
		PID=`cat $PIDFILE`
		echo $PROG already running: $PID
		exit 2;
	else
		cd $DIR
		daemon ./$PROG $OPTIONS
		RETVAL=$?
		echo
		[ $RETVAL -eq 0 ] && touch /var/lock/subsys/$PROG
		return $RETVAL
		fi
}

stop() {
	echo -n "Shutting down $PROG: "
	echo
	killproc $PROG
	echo
	rm -f /var/lock/subsys/$PROG
	return 0
}

case "$1" in
    start)
        start
        ;;
    stop)
        stop
        ;;
    status)
        status ns-slapd
        ;;
    restart)
        stop
        start
        ;;
    *)
        echo "Usage:  {start|stop|status|restart}"
        exit 1
        ;;
esac
exit $?
